version: '3.8'

services:
  my-app:
    image: my-app
    build:
      context: .
      args:
        PIP_EXTRA_INDEX_URL: http://host.docker.internal:3141/root/pypi
        TRUSTED_HOST: host.docker.internal